// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhT1DALG29Y0le1ecE_0FmOB4o7xmzjzE',
    appId: '1:367102815721:web:0c443185a7f6dc67f5ef78',
    messagingSenderId: '367102815721',
    projectId: 'skedmeds-v2',
    authDomain: 'skedmeds-v2.firebaseapp.com',
    storageBucket: 'skedmeds-v2.appspot.com',
    measurementId: 'G-YBGWE869QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHKPjVRo-P0SEZ1-QuVwMYUBxOoGq_Vw',
    appId: '1:367102815721:android:4c8bd5c0d3edcf56f5ef78',
    messagingSenderId: '367102815721',
    projectId: 'skedmeds-v2',
    storageBucket: 'skedmeds-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA21va0j9qj5nD3kPGo-MVBen4n_1R7PIQ',
    appId: '1:367102815721:ios:5ab12da2dfba6dd7f5ef78',
    messagingSenderId: '367102815721',
    projectId: 'skedmeds-v2',
    storageBucket: 'skedmeds-v2.appspot.com',
    iosBundleId: 'com.example.skedmeds',
  );
}
